### ISSUE TITLE
Not working with tslint 4

### ISSUE THREAD

**Issue by tmueller** [use-strict/tslint-formatter-vscode#1]
Hi,

i am trying to use this formatter with tslint 4. Unfortunately it throws the following error:

<pre>
Error: Cannot find module 'tslint/lib/lint'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([...]\node_modules\tslint-formatter-vscode\formatters\vscodeWarningFormatter.js:6:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
</pre>

It seems the filestructure of tslint has changed. I also tried to edit the path for the import to `var Lint = require("tslint/lib/linter");` , but that led to another error: 

<pre>
TypeError: Cannot read property 'AbstractFormatter' of undefined
    at Object.<anonymous> ([...]\node_modules\tslint-formatter-vscode\formatters\vscodeWarningFormatter.js:26:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadFormatter ([...]\node_modules\tslint\lib\formatterLoader.js:64:31)
    at Object.findFormatter ([...]\node_modules\tslint\lib\formatterLoader.js:42:25)
</pre>

**Comment by use-strict** [comment]
They moved everything to `index.js`. The fix should be:
```
import * as Lint from "tslint/lib/index";
```

The only problem is making it backwards compatible with tslint 3.

**Comment by use-strict** [comment]
Fixed and bumped major version to 2.

**Comment by tmueller** [comment]
Thanks for the fix. I appreciate your decision to break compatibility with version 3 of tslint and bump the major version. Makes it easier to keep up with new versions of tslint.
